### ISSUE TITLE
Destinations Modules

### ISSUE THREAD

**Issue by ndwilliams** [NSS-Day-Cohort-66/Cider-Falls-NiCHe#8]
Import necessary functions (getter Functions, destinationServicesList) and create DestinationCards function, which will iterate through destination array invoking destinationServicesList to return HTML string which includes destination location, title, and services.

**Comment by seatonct** [comment]
The html string created by the DistinationCards function should include a div (id="destinations") to contain all the cards as well as the destination card divs (class="destinationCard") created in the loop.
